#-- global.R --#

message("sf version: ", packageVersion("sf"))
library(sf) # GIS

suppressPackageStartupMessages({
  # core
  library(tidyverse)
  library(fst) # file storage
  library(httr2) # requests
  library(markdown)
  library(mirai) # async

  # shiny
  library(shiny)
  library(shinythemes)
  library(shinyWidgets)
  library(shinyjs)
  library(shinyalert)
  library(htmltools)

  # components
  library(leaflet)
  library(leaflet.extras)
  library(htmlwidgets)
  library(plotly)
})


# Dev settings -----------------------------------------------------------------

if (FALSE) {
  # add to renv without loading
  library(testthat)

  # RENV
  renv::init()
  renv::status()
  renv::restore()
  renv::update()
  renv::snapshot()
  renv::clean()
  renv::install("sf@1.0-24")
  renv::install("terra@1.9-11")
  renv::settings$ignored.packages("watcher", persist = TRUE)
  renv::install("watcher")

  # turn warnings into errors
  options(warn = 2)

  # disable forecasts for testing
  # options(cpn_forecast = FALSE)

  # Run unit tests
  testthat::test_dir("tests/testthat")

  # load test weather
  test_hourly_wx <- readRDS("tests/testthat/test_hourly_wx.rds")
  test_daily_wx <- build_daily(test_hourly_wx)
}

options(shiny.fullstacktrace = FALSE)


# Async setup ------------------------------------------------------------------

# set up background session for asynchronous tasks but not in tests
if (!identical(Sys.getenv("TESTTHAT"), "true")) {
  # start background workers
  mirai::daemons(4)

  # load required packages on workers
  mirai::everywhere({
    library(tidyverse)
    library(httr2)
    library(sf)
    library(fst)
  })
}


# Settings ---------------------------------------------------------------------

OPTS <- lst(
  ## general ----
  app_title = "Crop Risk Tool",
  app_header_color = "#00693c",
  app_header_badge = "cpn-badge.png",
  contact_email = "bbradford@wisc.edu",

  ## dates ----
  earliest_date = ymd("2015-1-1"),
  default_start_date = today() - months(1),

  ## map ----
  lat_lng_eps = 1e-4, # decimal precision
  map_bounds_wi = list(
    lat1 = 42.4,
    lat2 = 47.1,
    lng1 = -93.0,
    lng2 = -86.8
  ),
  map_bounds_us = list(
    lat1 = 24.0,
    lat2 = 50.0,
    lng1 = -125.5,
    lng2 = -66.0
  ),
  map_tiles = list(
    "ESRI Topo" = providers$Esri.WorldTopoMap,
    "Satellite" = providers$Esri.WorldImagery,
    "OpenStreetMap" = providers$OpenStreetMap,
    "Grey Canvas" = providers$CartoDB.Positron
  ),
  map_layers = list(
    grid = "Weather data grids"
  ),
  map_click_zoom = 10,

  ## sites ----
  # allowable names for site loading
  site_cols = c(
    name = "name",
    name = "location",
    lat = "lat",
    lat = "latitude",
    lng = "lng",
    lng = "long",
    lng = "longitude"
  ),
  max_sites = 25,
  validation_sites_ready = "No sites selected, click on the map or load sites in the sidebar.",
  validation_weather_ready = "No weather data downloaded yet for the selected dates.",

  ## data tab ----
  data_type_choices = list(
    "Hourly" = "hourly",
    "Daily" = "daily",
    "Moving averages" = "ma",
    "Growing degree days" = "gdd",
    "All" = "all"
    # "Model models" = "Model"
  ),

  ## risk tab ----
  model_group_choices = list(
    "Field crops" = "field",
    "Vegetable crops" = "vegetable",
    "Cover crops" = "cover",
    "Insects" = "insect"
  ),

  ## plotting ----
  plot_title_font = list(family = "Redhat Display", size = 14),
  plot_axis_font = list(family = "Redhat Text", size = 12),
  site_attr_cols = c(
    "site_id",
    "site_name",
    "site_lat",
    "site_lng"
  ),
  # most of these columns are generated by `om_wx_status()`
  grid_attr_cols = c(
    "grid_id",
    "grid_lat",
    "grid_lng",
    "elevation",
    "timezone",
    "tz_offset",
    "date_min",
    "date_max",
    "time_min",
    "time_max",
    "days_expected",
    "days_actual",
    "days_incomplete",
    "days_missing",
    "hours_expected",
    "hours_actual",
    "hours_missing"
  ),
  date_attr_cols = c(
    "datetime_utc",
    "datetime_local",
    "date",
    "yday",
    "year",
    "month",
    "day",
    "hour",
    "night",
    "date_since_night"
  ),
  daily_attr_cols = c("date", "yday", "year", "month", "day"),
  plot_default_cols = c(
    # hourly
    "temperature",
    "precipitation",
    "precipitation_cumulative",

    # daily
    "temperature_mean",
    "precipitation_daily",
    "precipitation_daily_cumulative",
    "wind_speed_max",

    # moving average
    "temperature_mean_7day",
    "relative_humidity_mean_7day",
    "soil_temp_mean_7day",

    # gdd
    "base_50_upper_86_cumulative",

    # all
    "temperature_hourly",
    "temperature_mean_daily",
    "precipitation_daily",
    "precipitation_daily_cumulative"
  ),
  plot_ignore_cols = c(site_attr_cols, grid_attr_cols, date_attr_cols),
)

# add keys unless testing
if (!identical(Sys.getenv("TESTTHAT"), "true")) {
  OPTS$open_meteo_key <- Sys.getenv("open_meteo_key")
  OPTS$google_geocoding_key <- Sys.getenv("google_geocoding_key")
  OPTS$google_places_key <- Sys.getenv("google_places_key")
}


# Utility functions ------------------------------------------------------------

# make this thing ignore both NULL and NA
`%||%` <- function(x, y) {
  if (length(na.omit(x)) == 0) y else x
}

# message and print an object to the console for testing
echo <- function(x) {
  message(deparse(substitute(x)), " <", paste(class(x), collapse = ", "), ">")
  print(x)
}

# display a message showing elapsed time since last timestamp
runtime <- function(label = "timestamp", ref = NULL) {
  t <- now()
  message(">> ", label, " [", t, "]")
  if (!is.null(ref)) {
    message(difftime(t, ref), " elapsed")
  }
  t
}

# swaps names and values in a list or vector
invert <- function(x) {
  y <- as(names(x), class(x))
  names(y) <- x
  y
}

# create named list from sublist elements
build_choices <- function(obj, name, value) {
  setNames(
    sapply(obj, \(x) x[[value]]),
    sapply(obj, \(x) x[[name]])
  )
}

# wrapper for shiny::isTruthy
is_truthy <- function(x) {
  shiny::isTruthy(x)
}

# return the first non-empty argument
first_truthy <- function(...) {
  for (arg in list(...)) {
    if (is_truthy(arg)) {
      return(arg)
    }
  }
  NULL
}

# restrict a value to between two extremes
clamp <- function(x, min, max) {
  pmax(min, pmin(max, x))
}

# return 2 element vector of min, max
minmax <- function(x) {
  c(min(x, na.rm = TRUE), max(x, na.rm = TRUE))
}

# rounds to nearest whole multiple of y
#' @param x number or vector
#' @param d divisor to round to
round_to <- function(x, d = 5) {
  round(x / d) * d
}


#' prints to tribble format in the console for pasting
#' @param df a data frame to convert to tribble
print_tribble <- function(df) {
  constructive::construct(df, opts_tbl_df("tribble"))
}


# Date/time helpers ------------------------------------------------------------

# calculate the difference in hours between two timestamps
hours_diff <- function(start, end) {
  as.integer(ceiling(difftime(end, start, units = "hours")))
}

if (FALSE) {
  hours_diff(now(), now())
  hours_diff(now() - hours(6), now())
  hours_diff(now() - days(1), now())
}


# Tibble helpers ---------------------------------------------------------------

#' create and insert cumulative count after a column
#' assumes data is already sorted chronologically
add_cumsum <- function(df, col) {
  newcol <- paste0(col, "_cumulative")
  df |>
    mutate(!!newcol := cumsum(.data[[col]]), .by = grid_id) |>
    relocate(all_of(newcol), .after = all_of(col))
}

if (FALSE) {
  test_hourly_wx |>
    add_cumsum("precipitation") |>
    pull(precipitation_cumulative)
}


#' df must have cols `grid_id`, `date`, `datetime_local`
add_date_cols <- function(df) {
  df |>
    mutate(
      yday = yday(date),
      year = year(date),
      month = month(date),
      day = day(date),
      hour = hour(datetime_local),
      night = !between(hour, 7, 19), # night is between 20:00 and 6:00
      date_since_night = as_date(datetime_local + hours(4)),
      .after = date,
      .by = grid_id
    )
}


# Summary functions ------------------------------------------------------------

## NA-safe summary functions ----

calc_sum <- \(x) if (all(is.na(x))) NA else sum(x, na.rm = TRUE)
calc_mean <- \(x) if (all(is.na(x))) NA else mean(x, na.rm = TRUE)
calc_min <- \(x) if (all(is.na(x))) NA else min(x, na.rm = TRUE)
calc_max <- \(x) if (all(is.na(x))) NA else max(x, na.rm = TRUE)


## data.table rolling functions ----

roll_mean <- function(x, width, align = "right") {
  data.table::frollmean(
    x,
    width,
    align = align,
    has.nf = TRUE,
    na.rm = TRUE,
    partial = !(align == "center")
  )
}

if (FALSE) {
  c(1:10, rep(NA, 5)) |>
    roll_mean(10, align = "center")
}

roll_mean_center <- function(x, width, na.rm = TRUE) {
  n <- length(x)
  half_r <- width %/% 2 # points to the right
  half_l <- width - half_r - 1L # points to the left (>= half_r for even width)

  not_na <- as.integer(!is.na(x))
  x0 <- data.table::fifelse(is.na(x), 0, x)

  # Accumulate rightward (right-aligned): covers [i - half_l - half_r, i]
  # We want [i - half_l, i + half_r], so shift results left by half_r
  rs <- data.table::frollsum(
    x0,
    width,
    align = "right",
    partial = TRUE,
    na.rm = FALSE
  )
  rc <- data.table::frollsum(
    not_na,
    width,
    align = "right",
    partial = TRUE,
    na.rm = FALSE
  )

  # Shift left by half_r to re-center
  idx <- c(seq(half_r + 1L, n), rep(NA_integer_, half_r))

  result <- rs[idx] / rc[idx]
  result
}

if (FALSE) {
  c(1:10, rep(NA, 5)) |>
    roll_mean_center(10)
}


roll_sum <- function(x, width, align = "right") {
  data.table::frollsum(
    x,
    width,
    align = align,
    has.nf = TRUE,
    na.rm = TRUE,
    partial = !(align == "center")
  )
}

# counts number consecutive runs of values above a threshold
count_runs <- function(vec, threshold, min_run) {
  runs <- run <- 0
  for (val in vec) {
    run <- if (val >= threshold) run + 1 else 0
    if (run == min_run) runs <- runs + 1
  }
  runs
}


# Unit conversions -------------------------------------------------------------

f_to_c <- \(x) (x - 32) / 1.8
c_to_f <- \(x) x * 1.8 + 32
mm_to_in <- \(x) x / 25.4
cm_to_in <- \(x) x / 2.54
m_to_ft <- \(x) x * 3.28084
mi_to_km <- \(x) x * 1.609
km_to_mi <- \(x) x / 1.609
kmh_to_mps <- \(x) x / 3.6
mps_to_mph <- \(x) x * 2.237
kPa_to_inHg <- \(x) x / 3.3864
mbar_to_inHg <- \(x) x / 33.864


#' Convert wind direction to degrees
#' @param dirs vector of wind direction strings
#' @returns vector of wind direction angles in degrees (unnamed)
wind_dir_to_deg <- function(dirs) {
  compass_dirs <- c(
    "N",
    "NNE",
    "NE",
    "ENE",
    "E",
    "ESE",
    "SE",
    "SSE",
    "S",
    "SSW",
    "SW",
    "WSW",
    "W",
    "WNW",
    "NW",
    "NNW"
  )
  degrees <- seq(0, 337.5, 22.5)

  degrees[match(dirs, compass_dirs)]
}

if (FALSE) {
  wind_dir_to_deg(c("N", "ENE", "NNW", "foo"))
}


# Unit lookup functions --------------------------------------------------------

#' List of weather variables, unit suffixes, and conversion functions
#' all derivative columns of each of these will start with the same text
#' e.g. temperature => temperature_min => temperature_min_30ma
conversion_lookup <- tribble(
  ~measure               , ~metric , ~imperial , ~conversion  ,
  "temperature"          , "°C"    , "°F"      , c_to_f       ,
  "dew_point_depression" , "°C"    , "°F"      , \(x) x * 1.8 , # C to F without offset
  "dew_point"            , "°C"    , "°F"      , c_to_f       ,
  "relative_humidity"    , "%"     , "%"       , \(x) x       ,
  "evapotranspiration"   , "mm"    , "in"      , mm_to_in     ,
  "precipitation"        , "mm"    , "in"      , mm_to_in     ,
  "rain"                 , "mm"    , "in"      , mm_to_in     ,
  "snowfall"             , "cm"    , "in"      , cm_to_in     ,
  "snow_depth"           , "m"     , "ft"      , m_to_ft      ,
  "pressure_msl"         , "kPa"   , "inHg"    , kPa_to_inHg  ,
  "wind_speed"           , "kmh"   , "mph"     , km_to_mi     ,
  "wind_gust"            , "kmh"   , "mph"     , km_to_mi     ,
  "wind_direction"       , "°"     , "°"       , \(x) x       ,
  "soil_temp"            , "°C"    , "°F"      , c_to_f       ,
  "soil_moisture"        , "%"     , "%"       , \(x) x       ,
  "base"                 , "GDD"   , "GDD"     , \(x) x
)


#' Converts all measures from default metric to imperial values
#' operates on any of the major datasets
#' @param df data frame from the hourly set or beyond
#' @returns df with column data converted
convert_measures <- function(df) {
  converted_cols <- character(0)
  for (i in seq_len(nrow(conversion_lookup))) {
    m <- conversion_lookup[i, ]
    eligible <- setdiff(
      names(df)[startsWith(names(df), m$measure)],
      converted_cols
    )
    if (length(eligible) > 0) {
      df <- mutate(df, across(all_of(eligible), m$conversion[[1]]))
      converted_cols <- c(converted_cols, eligible)
    }
  }
  df
}

if (FALSE) {
  test_hourly_wx <- readRDS("tests/testthat/test_hourly_wx.rds")
  test_hourly_wx |>
    select(-c(1:16)) |>
    convert_measures()
  test_hourly_wx |>
    build_daily() |>
    convert_measures()
}


#' Returns the unit name for the given column
#' used to append unit suffix in plotly
#' @param col_name data column name that needs a unit suffix
#' @param unit_system
find_unit <- function(col_name, unit_system = c("metric", "imperial")) {
  unit_system <- match.arg(unit_system)
  matched <- conversion_lookup |>
    rowwise() |>
    filter(grepl(measure, col_name))
  if (nrow(matched) == 1) matched[[unit_system]] else ""
}

if (FALSE) {
  find_unit("temperature", "metric")
}


#' Adds the unit suffix to each column name where appropriate
#' for exporting as CSV so unit is documented
#' @param df from the data pipeline
#' @param unit_system
#' @returns df with updated column names
rename_with_units <- function(df, unit_system = c("metric", "imperial")) {
  unit_system <- match.arg(unit_system)
  for (i in seq_len(nrow(conversion_lookup))) {
    m <- conversion_lookup[i, ]
    df <- df |>
      rename_with(
        .fn = ~ paste(.x, m[[unit_system]], sep = "_", recycle0 = TRUE),
        .cols = starts_with(m$measure)
      )
  }
  janitor::clean_names(df)
}

if (FALSE) {
  tibble(temperature = 1) |> rename_with_units("metric")
  tibble(temperature = 1) |> rename_with_units("imperial")
}


# Growing degree days ----------------------------------------------------------

#' Single sine method
#' to create GDDs with an upper threshold, calculate GDDs with the upper threshold
#' as the base temperature and subtract that value from the GDDs for the base temp
#' to implement a horizontal cutoff.
#' @param tmin minimum daily temperature
#' @param tmax maximum daily temperature
#' @param base base/lower temperature threshold
#' @param upper upper temperature threshold
#' @returns single sine growing degree days for one day
gdd_sine <- function(tmin, tmax, base, upper = 150) {
  tmin_adj <- pmin(tmin, tmax)
  tmax_adj <- pmax(tmin, tmax)

  avg <- (tmin_adj + tmax_adj) / 2
  alpha <- (tmax_adj - tmin_adj) / 2
  safe_alpha <- pmax(alpha, .Machine$double.eps)

  base_rad <- asin(pmax(-1, pmin(1, (base - avg) / safe_alpha)))
  upper_rad <- asin(pmax(-1, pmin(1, (upper - avg) / safe_alpha)))

  val_simple <- avg - base
  val_sine <- (1 / pi) *
    ((avg - base) * (pi / 2 - base_rad) + alpha * cos(base_rad))
  val_both <- (1 / pi) *
    ((avg - base) *
      (upper_rad - base_rad) +
      alpha * (cos(base_rad) - cos(upper_rad)) +
      (upper - base) * (pi / 2 - upper_rad))

  dplyr::case_when(
    is.na(tmin) | is.na(tmax) ~ NA_real_,
    tmax_adj <= base ~ 0,
    tmin_adj >= upper ~ upper - base, # both thresholds exceeded
    tmin_adj >= base ~ val_simple,
    tmax_adj <= upper ~ val_sine,
    TRUE ~ val_both
  )
}

if (FALSE) {
  gdd_sine(10:40, 0:30, 0, 10)
  gdd_sine(5:35, 0:30, 10)
}


# Location helpers -------------------------------------------------------------

# EPSG 4326 for use in Leaflet
# service_bounds <- readRDS("data/us_ca_clip.rds")

# transform to EPSG 3857 web mercator for intersecting points
# service_bounds_3857 <- st_transform(service_bounds, crs = 3857)

#' returns TRUE if location is within service boundary shapefile
#' @param lat latitude of point
#' @param lng longitude of point
#' @returns boolean
# validate_ll <- function(lat, lng) {
#   if (!is.numeric(lat) || !is.numeric(lng)) {
#     return(rep(FALSE, max(length(lat), length(lng))))
#   }
#   pts <- st_sfc(
#     mapply(function(lo, la) st_point(c(lo, la)), lng, lat, SIMPLIFY = FALSE),
#     crs = 4326
#   ) |>
#     st_transform(crs = 3857)
#   as.vector(st_intersects(pts, service_bounds_3857, sparse = FALSE))
# }

# simpler version without a region lock
#' @param lat:numeric latitude vector
#' @param lng:numeric longitude vector
#' @returns boolean vector
validate_ll <- function(lat, lng) {
  if (!is.numeric(lat) || !is.numeric(lng)) {
    return(rep(FALSE, max(length(lat), length(lng))))
  }
  between(lat, -180, 180) & between(lng, -180, 180)
}

if (FALSE) {
  validate_ll(45, -89)
  validate_ll(0, 0)
  validate_ll(seq(-300, 300, 100), seq(-300, 300, 100))
}


# UI builders ------------------------------------------------------------------

#' @param action which button type to create
#' @param site_id which site id
#' @param site_name site name, used to populate the edit popup
site_action_link <- function(
  action = c("edit", "save", "trash", "hide", "show"),
  site_id,
  site_name = ""
) {
  action <- match.arg(action)
  hovertext <- switch(
    action,
    edit = "Rename this site",
    save = "Pin this site to list",
    trash = "Delete this site",
    hide = "Hide this site",
    show = "Show this site"
  )
  onclick <- switch(
    action,
    edit = sprintf("editSite(%s, \"%s\")", site_id, site_name),
    save = sprintf("saveSite(%s)", site_id),
    trash = sprintf("trashSite(%s)", site_id),
    hide = sprintf("toggleSiteVisibility(%s)", site_id),
    show = sprintf("toggleSiteVisibility(%s)", site_id)
  )
  content <- as.character(switch(
    action,
    edit = icon("pen"),
    save = icon("thumbtack"),
    trash = icon("trash"),
    hide = icon("eye"),
    show = icon("eye-slash")
  ))
  sprintf(
    "<a style='cursor:pointer' title='%s' onclick='%s'>%s</a>",
    hovertext,
    onclick,
    content
  )
}

if (FALSE) {
  site_action_link("edit", 1, "foo")
  site_action_link("save", 1, "foo")
  site_action_link("trash", 1, "foo")
  site_action_link("hide", 1)
  site_action_link("show", 1)
}


#' Date button constructor for quick selection buttons
#' @param value:string on-click value passed to Shiny.setInputValue
#' @param label:string text for the button
#' @param btn_class:string style selection
build_date_btn <- function(
  value,
  label,
  btn_class = c("default", "primary")
) {
  btn_class <- match.arg(btn_class)
  HTML(
    sprintf(
      "<button class='btn btn-%s btn-xs action-button' onclick=\"this.blur(); Shiny.setInputValue('date_preset', '%s', {priority: 'event'});\">%s</button>",
      btn_class,
      value,
      label
    )
  )
}

if (FALSE) {
  build_date_btn("past_week", "Past week", "default")
}


#' Builds the 'More information' link that pops up the modal
#' @param model object created by Model() call
#' @returns HTML
build_modal_link <- function(model) {
  doc <- model$doc
  if (is.null(doc)) {
    return()
  }
  name <- model$name
  title <- paste(name, "information")
  onclick <- sprintf(
    "sendShiny('show_modal', {md: '%s', title: '%s'})",
    doc,
    title
  )
  shiny::HTML(
    sprintf(
      "<b><a style='cursor:pointer' title='%s' onclick=\"%s\">More information.</a></b>",
      title,
      onclick
    )
  )
}

if (FALSE) {
  build_modal_link(model_list$whitemold)
}


#' Shows a markdown file in a modal popup
#' @param md markdown file to display
#' @param title optional modal title
show_modal <- function(md, title = NULL) {
  if (!file.exists(md)) {
    warning(md, " does not exist")
    return()
  }

  m <- modalDialog(
    includeMarkdown(md),
    title = title,
    footer = modalButton("Close"),
    easyClose = TRUE
  )
  showModal(m)
}


#' Builds a div styled like an orange warning box
#' @param content text or tags to display in the warning box
build_warning_box <- function(content) {
  if (is.null(content)) {
    return()
  }

  div(
    class = "warning-box-container",
    div(
      style = "color: orange; font-size: 1.5em;",
      icon("warning")
    ),
    div(
      style = "font-size: small;",
      content
    )
  )
}

if (FALSE) {
  build_warning_box("alert")
}


# Site constructor -------------------------------------------------------------

sites_template <- tibble(
  id = integer(),
  name = character(),
  lat = numeric(),
  lng = numeric(),
  hidden = logical()
)

# Site constructor
Site <- function(name, lat, lng, id = 999) {
  list(
    id = id,
    name = name,
    lat = round_to(lat, OPTS$lat_lng_eps),
    lng = round_to(lng, OPTS$lat_lng_eps),
    hidden = FALSE
  )
}

if (FALSE) {
  Site("foo", 1, 2)
}


#' Make sure names read from csv are valid and safe to display
#' adds a counter after any duplicate names
#' @param str character vector of names
sanitize_loc_names <- function(str) {
  str <- trimws(gsub("<[^>]+>", "", str))
  str <- str_trunc(str, 30)
  Encoding(str) <- "UTF-8"
  tibble(name = str) |>
    mutate(count = row_number(), .by = name) |>
    mutate(name = if_else(count > 1, paste0(name, " (", count, ")"), name)) |>
    pull(name)
}

if (FALSE) {
  # should include "foo (2)"
  sanitize_loc_names(c("foo", "foo", "bar"))
  # should strip html
  sanitize_loc_names(c("foo", "bar", "<a href='bad'>baz</a>"))
}


#' Try read sites list from csv
#' @param fpath location of csv to read
load_sites <- function(fpath) {
  df <- read_csv(fpath, col_types = "c", show_col_types = FALSE)
  if (nrow(df) == 0) {
    stop("File was empty")
  }
  df <- df |>
    janitor::clean_names() |>
    select(any_of(OPTS$site_cols)) |>
    drop_na()
  if (!(all(c("name", "lat", "lng") %in% names(df)))) {
    stop("File did not contain [name] [lat] [lng] columns.")
  }
  df <- df |>
    mutate(name = sanitize_loc_names(name)) |>
    distinct(name, lat, lng) |>
    filter(validate_ll(lat, lng))
  if (nrow(df) == 0) {
    stop("No valid locations within service area.")
  }
  df |>
    mutate(id = row_number(), .before = 1) |>
    mutate(hidden = FALSE) |>
    head(OPTS$max_sites)
}

if (FALSE) {
  load_sites("data/example-sites.csv")
  load_sites("data/wisconet stns.csv")
}


# Cookie helpers ---------------------------------------------------------------

#' Parse and validate sites from browser cookie data
#' @param cookie_sites the $sites value from the parsed cookie (list of site records)
#' @returns tibble of valid sites with sequential IDs, or NULL if none
parse_cookie_sites <- function(cookie_sites) {
  if (length(cookie_sites) == 0) {
    return(NULL)
  }

  tryCatch(
    {
      bind_rows(cookie_sites) |>
        mutate(hidden = FALSE) |>
        select(all_of(names(sites_template))) |>
        filter(validate_ll(lat, lng)) |>
        distinct() |>
        head(OPTS$max_sites) |>
        mutate(id = row_number())
    },
    error = function(e) {
      message("Failed to read sites from cookie: ", e)
      NULL
    }
  )
}


#' Get the cache file path for a user ID, creating the cache directory if needed
#' @param user_id character user ID from the browser cookie
#' @returns file path string, or NULL if user_id is empty/invalid
get_cache_file <- function(user_id) {
  if (!is_truthy(user_id)) {
    return(NULL)
  }
  cache_path <- "cache"
  if (!dir.exists(cache_path)) {
    dir.create(cache_path)
  }
  file.path(cache_path, paste0(user_id, ".fst"))
}


# Cache cleaner ----------------------------------------------------------------

# Invoked on session end, clears any stale weather cache files
clean_old_caches <- function(max_age_days = 30) {
  cache_files <- list.files(
    path = "cache",
    pattern = ".*\\.fst",
    full.names = TRUE
  )
  old_files <- cache_files[file.mtime(cache_files) < Sys.Date() - max_age_days]
  if (length(old_files) > 0) {
    file.remove(old_files)
    message("Cleaned ", length(old_files), " old cache files")
  }
}

if (FALSE) {
  clean_old_caches()
}


# Load remaining code ----------------------------------------------------------

list.files("src", pattern = "\\.[Rr]$", full.names = TRUE) |>
  lapply(source)
