# Plot helpers ----

axis_defaults <- local({
  x <- y <- list(
    title = "",
    showticklabels = FALSE,
    showgrid = FALSE,
    showline = FALSE,
    zeroline = FALSE,
    fixedrange = TRUE,
    tickfont = OPTS$plot_axis_font
  )
  x$showticklabels <- TRUE
  x$hoverformat <- "<b>%b %d, %Y</b>"
  x$fixedrange <- FALSE

  list(x = x, y = y)
})


# expand axis range by percentage
expand_range <- function(lo, hi, amt = .05) {
  c(lo - abs(hi - lo) * amt, hi + abs(hi - lo) * amt)
}

# expand_range(0, 1)

#' add forecast annotation
#' @param xmax maximum x axis range. May be date or datetime axis
plotly_get_forecast_annot <- function(xmax) {
  if ("Date" %in% class(xmax)) {
    x <- today()
    label <- "Today"
  } else {
    x <- now()
    label <- "Now"
  }

  text <- list(list(
    yref = "paper",
    x = x,
    y = 1,
    text = label,
    showarrow = FALSE,
    opacity = .5,
    xanchor = "right",
    align = "right"
  ))

  vline <- list(list(
    type = "line",
    yref = "paper",
    x0 = x,
    x1 = x,
    y0 = .05,
    y1 = 1,
    line = list(color = "black", dash = "dash"),
    opacity = .25
  ))

  area <- list(list(
    type = "rect",
    fillcolor = "orange",
    line = list(opacity = 0),
    opacity = 0.05,
    yref = "paper",
    x0 = x,
    x1 = xmax,
    y0 = .05,
    y1 = 1,
    layer = "below"
  ))

  list(
    shapes = c(vline, area),
    annotations = text
  )
}

# plotly_get_forecast_annot(today())

#' create an annotation showing the risk period for a crop
#' @param start_date start of risk period
#' @param end_date end of risk period
#' @param xrange vector of two dates indicating the plotly x axis range
plotly_get_risk_period_annot <- function(
  start_date,
  end_date,
  xrange = c(start_date, end_date)
) {
  text_date_min <- max(start_date, xrange[1])
  text_date_max <- min(end_date, xrange[2])
  text_date <- text_date_min + (text_date_max - text_date_min) / 2

  text <- list(list(
    yref = "paper",
    x = text_date,
    y = 1,
    text = "Risk Period",
    showarrow = FALSE,
    opacity = .5,
    xanchor = "center",
    align = "center"
  ))

  vlines <- lapply(c(start_date, end_date), function(dt) {
    list(
      type = "line",
      yref = "paper",
      x0 = dt,
      x1 = dt,
      y0 = .05,
      y1 = 1,
      line = list(color = "maroon", weight = .5, dash = "dot"),
      opacity = .25
    )
  })

  area <- list(list(
    type = "rect",
    fillcolor = "red",
    line = list(opacity = 0),
    opacity = 0.05,
    yref = "paper",
    x0 = start_date,
    x1 = end_date,
    y0 = .05,
    y1 = 1,
    layer = "below"
  ))

  list(
    shapes = c(vlines, area),
    annotations = text
  )
}

# plotly_get_risk_period_annot(ymd("2025-7-1"), ymd("2025-8-15"))

#' Field crops disease plots
#' @param df data frame with model risk scores as generated by build_* functions
#' @param name name of the trace to show in the hovertext
#' @param xrange optional 2-element date vector forcing the x axis range
#' @param risk_period optional annotation generated by `plotly_get_risk_period_annot`
plot_risk <- function(df, name, xrange = NULL, risk_period = NULL) {
  x <- axis_defaults$x
  y <- axis_defaults$y
  x$range <- xrange

  # plot severity if present otherwise model_value
  if ("severity" %in% names(df)) {
    y$range <- expand_range(0, 4)
    df$y <- df$severity
  } else {
    y$range <- expand_range(0, 1)
    df$y <- df$model_value
  }

  # generate annotations
  shapes <- list()
  annot <- list()

  # forecast
  fc <- plotly_get_forecast_annot(xmax = xrange[2])
  shapes <- append(shapes, fc$shapes)
  annot <- append(annot, fc$annotations)

  # risk period
  yrs <- unique(year(df$date))
  if (!is.null(risk_period)) {
    for (yr in yrs) {
      dates <- ymd(paste(yr, risk_period))
      risk <- plotly_get_risk_period_annot(dates[1], dates[2], xrange)
      shapes <- append(shapes, risk$shapes)
      annot <- append(annot, risk$annotations)
    }
  }

  df |>
    plot_ly(x = ~date, y = ~y, height = 100) |>
    add_trace(
      name = name,
      text = ~value_label,
      type = "scatter",
      mode = "lines+markers",
      marker = list(color = ~risk_color),
      line = list(color = "black", width = 1),
      hovertemplate = "%{text}",
      hoverinfo = "text"
    ) |>
    add_trace(
      name = name,
      type = "bar",
      marker = list(
        color = ~ alpha(risk_color, .2),
        line = list(width = 0)
      ),
      hoverinfo = "none"
    ) |>
    layout(
      margin = list(l = 5, r = 5, b = 5, t = 5, pad = 5),
      xaxis = x,
      yaxis = y,
      bargap = 0,
      hovermode = "x unified",
      showlegend = FALSE
    ) |>
    layout(shapes = shapes, annotations = annot) |>
    config(displayModeBar = FALSE)
}

# test_hourly_wx |> filter(grid_id == sample(grid_id, 1)) |> build_daily() |> build_frogeye_leaf_spot() |> plot_risk(name = "Frogeye")

# determine whether data should go on y1 or y2
#' @param df data frame
#' @param cols which cols are we plotting
#' @returns df with name, axis ("y1", "y2") columns
assign_axes <- function(df, cols) {
  col_ranges <- df |>
    summarize(across(all_of(cols), ~ calc_max(.x))) |>
    pivot_longer(everything()) |>
    drop_na(value) |>
    mutate(
      value = sqrt(abs(value)),
      group = paste(
        str_extract(name, "^[^_]+"), # first part of the column name
        str_detect(name, "cumulative") # split cumulative away from non-cumulative
      )
    )

  # Get representative value per group (mean of member ranges)
  group_vals <- col_ranges |>
    summarize(group_value = mean(value), .by = group)

  # Assign axes at the group level
  group_axes <- group_vals |>
    mutate(y2 = group_value >= mean(group_value) - .5) |>
    mutate(y2 = if (mean(y2) > .5) !y2 else y2) |>
    mutate(axis = if_else(y2, "y2", "y1"))

  # Join back to individual columns
  col_ranges |>
    left_join(group_axes |> select(group, axis), by = "group") |>
    select(name, axis)
}

# weather data plot
#' @param df hourly, daily, or other dataset to plot
#' @param opts rest of arguments
build_data_plot <- function(df, sites, opts) {
  # change marker style depending on amount of data
  opts$mode <- ifelse(nrow(df) <= 100, "lines+markers", "lines")
  opts$linewidth <- ifelse(nrow(df) <= 500, 2, 1)

  # create plot title
  opts$title <- if (!opts$multi_site) {
    req(nrow(sites) == 1)
    sprintf(
      "%s data for %.3f°N, %.3f°W",
      opts$data_name,
      sites$lat,
      sites$lng
    )
  } else {
    site_locs <-
      with(
        filter(sites, id %in% opts$selected_ids),
        sprintf("Site %s: %.2f,%.2f", id, lat, lng)
      ) |>
      paste(collapse = " / ") |>
      str_wrap(120) |>
      str_replace_all("\\\n", "<br>")
    paste0(
      opts$data_name,
      " data<br><span style='font-size:12px;font-style:italic;'>",
      site_locs,
      "</span>"
    )
  }

  if ("datetime_local" %in% names(df)) {
    df$date <- df$datetime_local
  }

  # try to assign the columns to axes with values in similar ranges
  # also bunches the more numerous columns on the left
  col_ranges <- assign_axes(df, opts$cols)

  y1_title <- filter(col_ranges, axis == "y1")$name |>
    make_clean_names("title") |>
    paste(collapse = ", ")
  y2_title <- filter(col_ranges, axis == "y2")$name |>
    make_clean_names("title") |>
    paste(collapse = ", ")

  plt <- plot_ly() |>
    layout(
      title = list(
        text = opts$title,
        font = OPTS$plot_title_font
      ),
      hovermode = "x",
      showlegend = TRUE,
      margin = list(t = 50, r = 50),
      legend = list(
        orientation = "h",
        font = OPTS$plot_legend_font
      ),
      xaxis = list(
        range = opts$date_range
      ),
      yaxis = list(
        title = list(
          text = str_wrap(y1_title, 40),
          font = OPTS$plot_axis_font
        ),
        fixedrange = TRUE
      ),
      yaxis2 = list(
        overlaying = "y",
        side = "right",
        title = list(
          text = str_wrap(y2_title, 40),
          font = OPTS$plot_axis_font
        ),
        fixedrange = TRUE
      )
    ) |>
    config(
      displaylogo = FALSE,
      toImageButtonOptions = list(
        format = "png",
        filename = opts$filename,
        height = 800,
        width = 1500,
        scale = 1
      )
    )

  for (col in opts$cols) {
    col_name <- make_clean_names(col, "title")
    col_axis <- filter(col_ranges, name == col)$axis

    add_trace_to_plot <- function(plt, x, y, name) {
      add_trace(
        plt,
        x = x,
        y = y,
        name = name,
        type = "scatter",
        mode = opts$mode,
        yaxis = col_axis,
        hovertemplate = paste0(
          "%{y:.3~f}",
          find_unit(col, opts$unit_system)
        ),
        line = list(shape = "spline", width = opts$linewidth)
      )
    }

    if (opts$multi_site) {
      for (id in opts$selected_ids) {
        site_df <- df |> filter(site_id == id)
        name <- str_trunc(first(site_df$site_name), 15)
        plt <- add_trace_to_plot(
          plt,
          x = site_df$date,
          y = site_df[[col]],
          name = sprintf("%s: %s - %s", id, name, col_name)
        )
      }
    } else {
      plt <- add_trace_to_plot(
        plt,
        x = df$date,
        y = df[[col]],
        name = col_name
      )
    }
  }

  # indicate forecast
  if (isTruthy(opts$show_forecast)) {
    annot <- plotly_get_forecast_annot(xmax = opts$date_range[2])
    plt |> layout(shapes = annot$shapes, annotations = annot$annotations)
  } else {
    plt
  }
}
